# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs/agentic-starter-journey"
    schedule:
      interval: "semiannually"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "semiannually"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
