name: Test deployment

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/agentic-starter-journey

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./docs/agentic-starter-journey/package-lock.json

      - run: npm ci

      - name: Verify install
        run: node -e "require.resolve('next'); require.resolve('typescript')"

      - run: npm run typecheck

      - name: Test build website
        run: npm run build
